# Generated by Django 5.2.8 on 2025-11-11 17:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": None,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mesh_identity",
                    models.CharField(
                        help_text="Unique mesh network identity hash",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "public_key",
                    models.TextField(
                        db_index=True,
                        help_text="Cryptographic public key for the node",
                        unique=True,
                    ),
                ),
                ("firmware_version", models.CharField(default="v1.9.1", max_length=32)),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (0, "Repeater"),
                            (1, "Client"),
                        ],
                        default=0,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "altitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Altitude in meters",
                        max_digits=7,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Node",
                "verbose_name_plural": "Nodes",
            },
        ),
        migrations.CreateModel(
            name="RepeaterStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "batt_milli_volts",
                    models.PositiveIntegerField(help_text="Battery voltage in millivolts"),
                ),
                (
                    "curr_tx_queue_len",
                    models.PositiveIntegerField(help_text="Current transmit queue length"),
                ),
                (
                    "noise_floor",
                    models.SmallIntegerField(help_text="Noise floor in dBm"),
                ),
                (
                    "last_rssi",
                    models.SmallIntegerField(help_text="Last RSSI (Received Signal Strength Indicator) in dBm"),
                ),
                (
                    "last_snr",
                    models.SmallIntegerField(help_text="Last SNR (Signal-to-Noise Ratio) in dB"),
                ),
                (
                    "n_packets_recv",
                    models.PositiveBigIntegerField(help_text="Total packets received"),
                ),
                (
                    "n_packets_sent",
                    models.PositiveBigIntegerField(help_text="Total packets sent"),
                ),
                (
                    "n_recv_flood",
                    models.PositiveBigIntegerField(help_text="Flood packets received"),
                ),
                (
                    "n_recv_direct",
                    models.PositiveBigIntegerField(help_text="Direct packets received"),
                ),
                (
                    "n_sent_flood",
                    models.PositiveBigIntegerField(help_text="Flood packets sent"),
                ),
                (
                    "n_sent_direct",
                    models.PositiveBigIntegerField(help_text="Direct packets sent"),
                ),
                (
                    "n_flood_dups",
                    models.PositiveIntegerField(help_text="Duplicate flood packets"),
                ),
                (
                    "n_direct_dups",
                    models.PositiveIntegerField(help_text="Duplicate direct packets"),
                ),
                (
                    "total_air_time_secs",
                    models.PositiveBigIntegerField(help_text="Total air time in seconds (TX)"),
                ),
                (
                    "total_rx_air_time_secs",
                    models.PositiveBigIntegerField(help_text="Total air time in seconds (RX)"),
                ),
                (
                    "total_up_time_secs",
                    models.PositiveBigIntegerField(help_text="Total uptime in seconds"),
                ),
                (
                    "err_events",
                    models.PositiveIntegerField(help_text="Number of error events"),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_readings",
                        to="max.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "Node Telemetry",
                "verbose_name_plural": "Node Telemetry",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="NeighbourInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advert_timestamp",
                    models.PositiveBigIntegerField(help_text="Advertisement timestamp from firmware"),
                ),
                (
                    "heard_timestamp",
                    models.PositiveBigIntegerField(help_text="Last heard timestamp from firmware"),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "snr",
                    models.SmallIntegerField(help_text="Signal-to-Noise Ratio (multiplied by 4 in firmware)"),
                ),
                (
                    "neighbour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heard_by",
                        to="max.node",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighbours",
                        to="max.node",
                    ),
                ),
            ],
            options={
                "unique_together": {("node", "neighbour")},
            },
        ),
        migrations.AddField(
            model_name="node",
            name="estimated_range",
            field=models.PositiveIntegerField(
                default=1000, help_text="Estimated coverage range in meters (used for map visualization)"
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.CreateModel(
            name="SignalMeasurement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(help_text="GPS coordinates (lon, lat)", srid=4326),
                ),
                (
                    "altitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Altitude in meters (from browser geolocation, may be null)",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "gps_accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="GPS horizontal accuracy in meters (from browser)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("rssi", models.SmallIntegerField(help_text="Received Signal Strength Indicator in dBm")),
                ("snr", models.SmallIntegerField(help_text="Signal-to-Noise Ratio in dB")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session_id",
                    models.UUIDField(blank=True, db_index=True, help_text="Groups measurements from same session", null=True),
                ),
                (
                    "collector_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who collected this measurement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="measurements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="signal_measurements", to="max.node"
                    ),
                ),
            ],
            options={
                "verbose_name": "Signal Measurement",
                "verbose_name_plural": "Signal Measurements",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["target_node", "-timestamp"], name="max_signalm_target__1ea2ce_idx"),
                    models.Index(fields=["session_id"], name="max_signalm_session_94e660_idx"),
                ],
            },
        ),
    ]
