# Generated by Django 6.0 on 2025-12-12 20:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("max", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MappingSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, help_text="Description of the mapping session")),
            ],
            options={
                "verbose_name": "Mapping Session",
                "verbose_name_plural": "Mapping Sessions",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Trace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(help_text="GPS coordinates (lon, lat)", srid=4326),
                ),
                (
                    "altitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Altitude in meters (from browser geolocation, may be null)",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "gps_accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="GPS horizontal accuracy in meters (from browser)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "snr_to_target",
                    models.FloatField(default=0.0, help_text="SNR at target node (our signal reaching the repeater) in dB"),
                ),
                (
                    "snr_from_target",
                    models.FloatField(default=0.0, help_text="SNR at our device (repeater's signal reaching us) in dB"),
                ),
                ("trace_success", models.BooleanField(default=False, help_text="Whether the trace command succeeded")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Trace",
                "verbose_name_plural": "Traces",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RemoveIndex(
            model_name="signalmeasurement",
            name="max_signalm_target__1ea2ce_idx",
        ),
        migrations.RemoveIndex(
            model_name="signalmeasurement",
            name="max_signalm_session_94e660_idx",
        ),
        migrations.AddField(
            model_name="mappingsession",
            name="target_node",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="max.node"),
        ),
        migrations.AddField(
            model_name="mappingsession",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="trace",
            name="session",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="max.mappingsession"),
        ),
        migrations.RemoveField(
            model_name="signalmeasurement",
            name="collector_user",
        ),
        migrations.RemoveField(
            model_name="signalmeasurement",
            name="target_node",
        ),
        migrations.AddIndex(
            model_name="mappingsession",
            index=models.Index(fields=["user", "-start_time"], name="max_mapping_user_id_f232b6_idx"),
        ),
        migrations.AddIndex(
            model_name="mappingsession",
            index=models.Index(fields=["target_node", "-start_time"], name="max_mapping_target__06e6eb_idx"),
        ),
        migrations.AddIndex(
            model_name="trace",
            index=models.Index(fields=["session", "-timestamp"], name="max_trace_session_712364_idx"),
        ),
        migrations.DeleteModel(
            name="SignalMeasurement",
        ),
    ]
