# Generated by Django 6.0 on 2025-12-05 14:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0002_node_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='node',
            name='longitude',
        ),
        migrations.AddField(
            model_name='node',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic location (lon, lat)', null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='SignalMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='GPS coordinates (lon, lat)', srid=4326)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, help_text='Altitude in meters (from browser geolocation, may be null)', max_digits=7, null=True)),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='GPS horizontal accuracy in meters (from browser)', max_digits=6, null=True)),
                ('rssi', models.SmallIntegerField(help_text='Received Signal Strength Indicator in dBm')),
                ('snr', models.SmallIntegerField(help_text='Signal-to-Noise Ratio in dB')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_id', models.UUIDField(blank=True, db_index=True, help_text='Groups measurements from same session', null=True)),
                ('collector_user', models.ForeignKey(blank=True, help_text='User who collected this measurement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to=settings.AUTH_USER_MODEL)),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_measurements', to='max.node')),
            ],
            options={
                'verbose_name': 'Signal Measurement',
                'verbose_name_plural': 'Signal Measurements',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target_node', '-timestamp'], name='max_signalm_target__1ea2ce_idx'), models.Index(fields=['session_id'], name='max_signalm_session_94e660_idx')],
            },
        ),
    ]
