# Generated by Django 6.0.3 on 2026-03-04 22:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mesh_identity", models.CharField(help_text="Unique mesh network identity hash", max_length=64, unique=True)),
                (
                    "public_key",
                    models.TextField(db_index=True, help_text="Cryptographic public key for the node", unique=True),
                ),
                ("firmware_version", models.CharField(default="v1.9.1", max_length=32)),
                ("role", models.IntegerField(choices=[(0, "Repeater"), (1, "Client")], default=0)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                (
                    "altitude",
                    models.DecimalField(blank=True, decimal_places=2, help_text="Altitude in meters", max_digits=7, null=True),
                ),
                (
                    "estimated_range",
                    models.PositiveIntegerField(
                        default=1000, help_text="Estimated coverage range in meters (used for map visualization)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Node",
                "verbose_name_plural": "Nodes",
            },
        ),
        migrations.CreateModel(
            name="FieldTest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, help_text="Description of the field test")),
                ("target_node", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="metro.node")),
            ],
            options={
                "verbose_name": "Field Test",
                "verbose_name_plural": "Field Tests",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="RepeaterStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("batt_milli_volts", models.PositiveIntegerField(help_text="Battery voltage in millivolts")),
                ("curr_tx_queue_len", models.PositiveIntegerField(help_text="Current transmit queue length")),
                ("noise_floor", models.SmallIntegerField(help_text="Noise floor in dBm")),
                ("last_rssi", models.SmallIntegerField(help_text="Last RSSI (Received Signal Strength Indicator) in dBm")),
                ("last_snr", models.SmallIntegerField(help_text="Last SNR (Signal-to-Noise Ratio) in dB")),
                ("n_packets_recv", models.PositiveBigIntegerField(help_text="Total packets received")),
                ("n_packets_sent", models.PositiveBigIntegerField(help_text="Total packets sent")),
                ("n_recv_flood", models.PositiveBigIntegerField(help_text="Flood packets received")),
                ("n_recv_direct", models.PositiveBigIntegerField(help_text="Direct packets received")),
                ("n_sent_flood", models.PositiveBigIntegerField(help_text="Flood packets sent")),
                ("n_sent_direct", models.PositiveBigIntegerField(help_text="Direct packets sent")),
                ("n_flood_dups", models.PositiveIntegerField(help_text="Duplicate flood packets")),
                ("n_direct_dups", models.PositiveIntegerField(help_text="Duplicate direct packets")),
                ("total_air_time_secs", models.PositiveBigIntegerField(help_text="Total air time in seconds (TX)")),
                ("total_rx_air_time_secs", models.PositiveBigIntegerField(help_text="Total air time in seconds (RX)")),
                ("total_up_time_secs", models.PositiveBigIntegerField(help_text="Total uptime in seconds")),
                ("err_events", models.PositiveIntegerField(help_text="Number of error events")),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="telemetry_readings", to="metro.node"
                    ),
                ),
            ],
            options={
                "verbose_name": "Node Telemetry",
                "verbose_name_plural": "Node Telemetry",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Trace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(help_text="GPS coordinates (lon, lat)", srid=4326),
                ),
                (
                    "altitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Altitude in meters (from browser geolocation, may be null)",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "gps_accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="GPS horizontal accuracy in meters (from browser)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "snr_to_target",
                    models.FloatField(default=0.0, help_text="SNR at target node (our signal reaching the repeater) in dB"),
                ),
                (
                    "snr_from_target",
                    models.FloatField(default=0.0, help_text="SNR at our device (repeater's signal reaching us) in dB"),
                ),
                ("trace_success", models.BooleanField(default=False, help_text="Whether the trace command succeeded")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("field_test", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="metro.fieldtest")),
            ],
            options={
                "verbose_name": "Trace",
                "verbose_name_plural": "Traces",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="NeighbourInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("advert_timestamp", models.PositiveBigIntegerField(help_text="Advertisement timestamp from firmware")),
                ("heard_timestamp", models.PositiveBigIntegerField(help_text="Last heard timestamp from firmware")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("snr", models.SmallIntegerField(help_text="Signal-to-Noise Ratio (multiplied by 4 in firmware)")),
                (
                    "neighbour",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="heard_by", to="metro.node"),
                ),
                (
                    "node",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="neighbours", to="metro.node"),
                ),
            ],
            options={
                "unique_together": {("node", "neighbour")},
            },
        ),
        migrations.AddIndex(
            model_name="fieldtest",
            index=models.Index(fields=["target_node", "-start_time"], name="metro_field_target__330bac_idx"),
        ),
        migrations.AddIndex(
            model_name="trace",
            index=models.Index(fields=["field_test", "-timestamp"], name="metro_trace_field_t_ad1774_idx"),
        ),
        migrations.CreateModel(
            name="HotspotConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ssid", models.CharField(blank=True, help_text="WiFi hotspot SSID", max_length=255)),
                (
                    "password",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text="Encrypted WiFi password"),
                ),
            ],
            options={
                "verbose_name": "Hotspot Configuration",
                "verbose_name_plural": "Hotspot Configuration",
                "constraints": [models.CheckConstraint(condition=models.Q(("id", 1)), name="hotspot_config_singleton")],
            },
        ),
        migrations.RemoveIndex(
            model_name="fieldtest",
            name="metro_field_target__330bac_idx",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="hotspotconfig",
                    name="hotspot_config_singleton",
                ),
            ],
        ),
        migrations.DeleteModel(
            name="HotspotConfig",
        ),
        migrations.RemoveIndex(
            model_name="trace",
            name="metro_trace_field_t_ad1774_idx",
        ),
        migrations.RemoveField(
            model_name="trace",
            name="field_test",
        ),
        migrations.DeleteModel(
            name="FieldTest",
        ),
        migrations.DeleteModel(
            name="Trace",
        ),
    ]
