# Generated by Django 6.0.3 on 2026-03-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='path',
            field=models.CharField(blank=True, help_text='Routing path for ping. Blank=flood, 4-char hash=direct, comma-separated=multi-hop (e.g. 46,93,46)', max_length=255),
        ),
    ]
